development:
  adapter: mysql
  encoding: utf8
  database: mpr_dev
  pool: 5
  username: ruby
  password: rubypass
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
